@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoiZWxlbmFnYXJjaWEiLCJlbWFpbCI6ImVsZW5hZ2FyY2lhQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYzNTUxODk3LCJleHAiOjE3OTUwODc4OTd9.COtbMG-B8RWr7UdBPEqQk5nVd3G_d1i8nPG5Xw6-g-s
@URL_AZURE = https://traveltogetherapi-bfd4dhgfb9dhhnbe.spaincentral-01.azurewebsites.net/api
@URL_LOCAL = http://localhost:3000/api/favorites

@URL = {{URL_LOCAL}}

### Petición 0 : LISTAR TODAS LOS FAVORITES
GET {{URL}}
Authorization: Bearer {{TOKEN}}

### Petición 1 : LISTAR FAVORITES POR ID
GET {{URL}}/1
Authorization: Bearer {{TOKEN}}

### Petición 3 : LISTAR FAVORITES POR USER_ID
GET {{URL}}/user/1
Authorization: Bearer {{TOKEN}}

### Petición 3 : LISTAR FAVORITES POR TRIP_ID
GET {{URL}}/trip/1
Authorization: Bearer {{TOKEN}}

### - Create FAVORITES
POST {{URL}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "trip_id": 13
}

### - updateFavoritesById
PUT {{URL}}/21
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "trip_id": 63
}

### Petición 4 : ELIMINAR FAVORITES BY ID
DELETE {{URL}}/21
Authorization: Bearer {{TOKEN}}