@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoiZWxlbmFnYXJjaWEiLCJlbWFpbCI6ImVsZW5hZ2FyY2lhQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYyNzAzNTc5LCJleHAiOjE3NjI3MTA3Nzl9.DGinLb3bWqRh2dRY8RvJ-GZqgMzUuHcvS9kb4S6OAMo
@URL = http://localhost:3000/api/trips

### Petición 1 : LISTAR TODOS LOS VIAJES (PROTEGIDO)
GET {{URL}}
Authorization: Bearer {{TOKEN}}

### Petición 2 : LISTAR VIAJES CON PAGINACIÓN Y FILTRADO (PROTEGIDO)
GET {{URL}}?page=1&per_page=2
Authorization: Bearer {{TOKEN}}

### Petición 3 : VER DETALLES DE UN VIAJE (PROTEGIDO)
GET {{URL}}/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoiZWxlbmFnYXJjaWEiLCJlbWFpbCI6ImVsZW5hZ2FyY2lhQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYyNzAzNTc5LCJleHAiOjE3NjI3MTA3Nzl9.DGinLb3bWqRh2dRY8RvJ-GZqgMzUuHcvS9kb4S6OAMo

### Petición 4 : CREAR UN NUEVO VIAJE
POST {{URL}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "origin": "Madrid",
  "destination": "Tromsø, Noruega",
  "title": "Caza de la Aurora Boreal en el Ártico",
  "description": "Una expedición emocionante para presenciar la majestuosa Aurora Boreal en Tromsø, Noruega. Incluye actividades como paseos en trineo de perros, visitas a pueblos Sami y noches en acogedoras cabañas árticas.",
  "creator_id": 12,
  "start_date": "2026-02-10 00:00:00",
  "end_date": "2026-02-15 00:00:00",
  "estimated_cost": "950.00",
  "min_participants": 5,
  "transport": "Avión",
  "accommodation": "Cabaña compartida",
  "itinerary": "Día 1: Llegada a Tromsø y orientación. Día 2: Paseo en trineo de perros y búsqueda de la Aurora Boreal. Día 3: Visita a un pueblo Sami y cultura local. Día 4: Tiempo libre y actividades opcionales. Día 5: Desayuno y egreso a casa.",
  "status": "open",
  "latitude": "69.64920000",
  "longitude": "18.95530000",
  "created_at": "2025-02-11 00:00:00",
  "updated_at": "2025-02-11 00:00:00"
}

### Petición 5 : ACTUALIZAR UN VIAJE (ID 6)
PUT {{URL}}/6
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "origin": "Madrid",
  "destination": "Tromsø, Noruega",
  "title": "Caza de la Aurora Boreal en el Ártico",
  "description": "Una expedición emocionante para presenciar la majestuosa Aurora Boreal en Tromsø, Noruega. Incluye actividades como paseos en trineo de perros, visitas a pueblos Sami y noches en acogedoras cabañas árticas.",
  "creator_id": 12,
  "start_date": "2026-02-10 00:00:00",
  "end_date": "2026-02-15 00:00:00",
  "estimated_cost": "950.00",
  "min_participants": 5,
  "transport": "Avión",
  "accommodation": "Cabaña compartida",
  "itinerary": "Día 1: Llegada a Tromsø y orientación. Día 2: Paseo en trineo de perros y búsqueda de la Aurora Boreal. Día 3: Visita a un pueblo Sami y cultura local. Día 4: Tiempo libre y actividades opcionales. Día 5: Desayuno y egreso a casa.",
  "status": "open",
  "latitude": "69.64920000",
  "longitude": "18.95530000",
  "created_at": "2025-02-11 00:00:00",
  "updated_at": "2025-02-11 00:00:00"
}

### Petición 6 : ELIMINAR UN VIAJE (ID 6)
DELETE http://localhost:3000/api/trips/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoiZWxlbmFnYXJjaWEiLCJlbWFpbCI6ImVsZW5hZ2FyY2lhQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYyNzAzNTc5LCJleHAiOjE3NjI3MTA3Nzl9.DGinLb3bWqRh2dRY8RvJ-GZqgMzUuHcvS9kb4S6OAMo