@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsInVzZXJuYW1lIjoiZWxlbmFnYXJjaWEiLCJlbWFpbCI6ImVsZW5hZ2FyY2lhQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYyNzAzNTc5LCJleHAiOjE3NjI3MTA3Nzl9.DGinLb3bWqRh2dRY8RvJ-GZqgMzUuHcvS9kb4S6OAMo
@URL = http://localhost:3000/api/images

### Petición 1 : LISTAR IMAGEN POR ID
GET {{URL}}/1
Authorization: Bearer {{TOKEN}}

### Petición 2 : LISTAR IMAGENES POR TRIP_ID
GET {{URL}}/trips/3
Authorization: Bearer {{TOKEN}}

### Petición 3 : LISTAR IMAGENES POR USER_ID
GET {{URL}}/users/1
Authorization: Bearer {{TOKEN}}

### Petición 4 : ELIMINAR IMAGEN BY ID
DELETE {{URL}}/5
Authorization: Bearer {{TOKEN}}