@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksInVzZXJuYW1lIjoibGFsc2luYSIsImVtYWlsIjoibGFsc2luYTg4M0BnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjUwNTIwNDUsImV4cCI6MTc5NjU4ODA0NX0._0zFBeqTkav2iD0QXKZwWZ4HjaUfSRT8YbkzbPOdBiw
@URL_AZURE = https://traveltogetherapi-bfd4dhgfb9dhhnbe.spaincentral-01.azurewebsites.net/api
@URL_LOCAL = http://localhost:3000/api
 
@URL = {{URL_LOCAL}}
 

POST {{URL}}/users/register
Content-Type: application/json

{
  "username": "lalsina",
  "email": "lalsina883@gmail.com",
  "password": "1234",
  "image": "https://images.piclumen.com/normal/20251109/19/b332132861a84d339ab55a617e0289ed.webp",
  "phone": "669361891",
  "bio": "Me gusta la aventura",
  "interests": "musica, animales, viajar"
}

###
POST {{URL}}/users/login
Content-Type: application/json

{
  "email": "u2714507676@gmail.com",
  "password": "12345"
}

###
GET http://localhost:3000/api/users
// Authorization: Bearer {{TOKEN}}

###
GET http://localhost:3000/api/users?page=1&per_page=5&search=esmeralda
Authorization: Bearer {{TOKEN}}

###
GET http://localhost:3000/api/users/1
// Authorization: Bearer {{TOKEN}}

###
PUT http://localhost:3000/api/users/38
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "username": "lalsina",
  "email": "lalsina883@gmail.com",
  "image": "https://images.piclumen.com/normal/20251109/19/b332132861a84d339ab55a617e0289ed.webp",
  "phone": "669361891",
  "bio": "Me gusta la aventura x 2",
  "interests": "musica, animales, viajar",
  "password": "1234",  
  "is_active": 1
}

###
DELETE http://localhost:3000/api/users/39
Authorization: Bearer {{TOKEN}}