POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "leopoldo",
  "email": "leopoldo@gmail.com",
  "password": "1234",
  "image": "https://i.pravatar.cc/150?u=leopoldo",
  "phone": "600123456",
  "bio": "le gusta ser leopoldo",
  "interests": "music sin mas"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "leopoldo@gmail.com",
  "password": "1234"
}