@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsInVzZXJuYW1lIjoiTGx1aXMiLCJlbWFpbCI6ImxhbHNpbmE4ODNAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjU2NjEzMjQsImV4cCI6MTc5NzE5NzMyNH0.COMZikBC7U1Oeu19Vmsb0qdtslFokN6s3ukN5W3Vp9I
@URL_AZURE = https://traveltogetherapi-bfd4dhgfb9dhhnbe.spaincentral-01.azurewebsites.net/api/messages
@URL_LOCAL = http://localhost:3000/api/messages

@URL = {{URL_LOCAL}}

### Petición 0 : LISTAR TODAS LAS MESSAGES
GET {{URL}}
Authorization: Bearer {{TOKEN}}

### Petición 0 : LISTAR TODAS LAS MESSAGES con un where chulo
GET {{URL}}/where?page=1&per_page=5&where=receiver_id:1 and sender_id:3 and trip_id:63 and group_id:1
Authorization: Bearer {{TOKEN}}

### Petición 1 : LISTAR MESSAGES POR ID
GET {{URL}}/7
Authorization: Bearer {{TOKEN}}

### - Create MESSAGES
POST {{URL}}
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "message": "Un mensaje que creo para probar",
  "receiver_id": 44,
  "trip_id": 86
  // "group_id": 2
}

### - updateMessageById
PUT {{URL}}/7
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "message": "ahora es otro mensaje"
}

### Petición 4 : ELIMINAR MESSAGES BY ID
DELETE {{URL}}/7
Authorization: Bearer {{TOKEN}}